image: s2shape/s2shape-test-harness:latest

stages:
  - build
  - test

variables:
  HIVE_HOST: hive
  HIVE_PORT: "10000"
  HIVE_DB: default
  HIVE_USER: hive
  HIVE_PASS: anonymous

before_script:
  - dotnet restore -s https://www.myget.org/F/s2/ -s https://api.nuget.org/v3/index.json

build:
  stage: build
  script:
    - dotnet build

test:
  stage: test

  services:
    - name: nagasuga/docker-hive
      alias: hive
      command: [/bin/bash, -c, 'cd /usr/local/hive && ./bin/hiveserver2' ]

  script:
    - ROOT_PROJECT_PATH=$(pwd)
    - dotnet build
    - dotnet publish
    - cd $ROOT_PROJECT_PATH/HiveSupplyCollectorLoader/bin/Debug/netcoreapp2.2/publish
    - cp -f /SupplyCollectorDataLoader/SupplyCollectorDataLoader/bin/Debug/netcoreapp2.2/SupplyCollectorDataLoader.runtimeconfig.json .
    - dotnet SupplyCollectorDataLoader.dll -init HiveSupplyCollector hive2://$HIVE_USER:$HIVE_PASS@$HIVE_HOST:$HIVE_PORT/$HIVE_DB
    - dotnet SupplyCollectorDataLoader.dll -xunit HiveSupplyCollector hive2://$HIVE_USER:$HIVE_PASS@$HIVE_HOST:$HIVE_PORT/$HIVE_DB
    - cd $ROOT_PROJECT_PATH
    - dotnet test

load_test:
  stage: test

  services:
    - name: nagasuga/docker-hive
      alias: hive
      command: [/bin/bash, -c, 'cd /usr/local/hive && ./bin/hiveserver2' ]

  script:
    - ROOT_PROJECT_PATH=$(pwd)
    - dotnet build
    - dotnet publish
    - cd $ROOT_PROJECT_PATH/HiveSupplyCollectorLoader/bin/Debug/netcoreapp2.2/publish
    - cp -f /SupplyCollectorDataLoader/SupplyCollectorDataLoader/bin/Debug/netcoreapp2.2/SupplyCollectorDataLoader.runtimeconfig.json .
    - dotnet SupplyCollectorDataLoader.dll -init HiveSupplyCollector hive2://$HIVE_USER:$HIVE_PASS@$HIVE_HOST:$HIVE_PORT/$HIVE_DB
    - dotnet SupplyCollectorDataLoader.dll -xunit HiveSupplyCollector hive2://$HIVE_USER:$HIVE_PASS@$HIVE_HOST:$HIVE_PORT/$HIVE_DB
    - dotnet SupplyCollectorDataLoader.dll -samples HiveSupplyCollector hive2://$HIVE_USER:$HIVE_PASS@$HIVE_HOST:$HIVE_PORT/$HIVE_DB TestCollection Test1:int,Test2:string,Test3:bool,Test4:double,Test5 1000000
    - cd $ROOT_PROJECT_PATH/HiveSupplyCollectorTests/bin/Debug/netcoreapp2.2/publish
    - SupplyCollectorTestHarness
